version: "3.7"
services:
  termgres:
    image: termgres:latest
    restart: always
    environment:
      - POSTGRES_USER=termgres
      - POSTGRES_PASSWORD=termgres
    ports:
      - "5432:5432"
    volumes:
      - termgres:/var/lib/termgresql/data
volumes:
  termgres:
